### ISSUE TITLE
infografia_Gestion_de_Proyectos

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-carlos-chrs#2]
![Infografía Algunas características que hacen a un excelente maestro o maestra 15 de mayo día del maestro](https://user-images.githubusercontent.com/79929498/186507300-f972e329-d313-4be6-b6d7-af79684e17e0.jpg)

**Comment by bg55-a** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
